[stripe]
secret_key = "sk_test_51QdMi2H2h13vRbN8fdWucmyH956JFZu92WmHk84gNjBhSAjMlHEAk4WMO69BJOInCWRhVxdYZ2SViHIledY79yw800J9VP0hzk"          
publishable_key = "pk_test_51QdMi2H2h13vRbN80LjjhtdMSCsWT2GJlqO8oYfbDD15mNAw8QwyhwQjjYBv76nKbjAgnRkDvWpdNDeefCiV6W7700zeoauL3g"  

[stripe_prices]
one_deal = "prod_TSUsQZpptXXU0X"         
annual = "prod_TSUtEjkojuf8Ql"         
